### ISSUE TITLE
Access token usage

### ISSUE THREAD

**Issue by andrew2net** [relaton/support#6]
The `relaton/relaton-data-bipm` repo needs to clone `relaton/rawdata-bipm-metrologia` private repo. We need to use an access token to clone the repo. I've tried to set an environment variable:
```yaml
env:
  RELATON_CI_PAT: ${{ secrets.RELATON_CI_PAT }}
jobs:
  uses: relaton/support/.github/workflows/crawler.yml@master
```
and use it in the `crawler.rb` script:
```ruby
system('git clone https://$RELATON_CI_PAT@github.com/relaton/rawdata-bipm-metrologia rawdata-bipm-metrologia')
```
but without success. The access token works if it's used in a checkout action:
```yaml
    - uses: actions/checkout@v2
      with:
        repository: relaton/rawdata-bipm-metrologia
        token: ${{ secrets.RELATON_CI_PAT }}
        path: rawdata-bipm-metrologia
```
but it seems impossible to use another action in one job with the reusable workflow.
Any suggestions?
